name: analytics
description: |-
  Submitting anonymized usage information.
  This usage helps us identify any problems with the integrations.
  The sent data only contains information about steps (id, version, runtime, error), NO logs or other data is included.
  For more information visit: https://github.com/bitrise-io/bitrise/blob/master/README.md
trigger: DidFinishRun
executable:
  osx: https://github.com/bitrise-core/bitrise-plugins-analytics/releases/download/0.9.3/analytics-Darwin-x86_64
  linux: https://github.com/bitrise-core/bitrise-plugins-analytics/releases/download/0.9.3/analytics-Linux-x86_64
requirements:
- tool: bitrise
  min_version: 1.3.0
  max_version: ""
